name: Main Deployment
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    unit-test-webapp:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18.x]
        defaults:
            run:
                working-directory: webapp
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm ci --legacy-peer-deps
            - run: npm run test:prod
    
    unit-test-restapi:
        runs-on: ubuntu-latest
        env:
            PRODUCTION_DATABASE_URL: ${{secrets.PRODUCTION_DATABASE_URL }}
            SECRET: ${{secrets.SECRET }}
            FILEPATH: ${{secrets.FILEPATH }}
            EMAIL: ${{secrets.EMAIL }}
            REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN }}
            CLIENT_ID: ${{secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{secrets.CLIENT_SECRET }}
            REDIRECT_URI: ${{secrets.REDIRECT_URI }}

        services:
            postgres:
                image: postgres

                env:
                    POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD }}
                    POSTGRES_USER: ${{secrets.POSTGRES_USER}}
                    POSTGRES_DB: ${{secrets.POSTGRES_DB}}
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        strategy:
            matrix:
              node-version: [18.x]
        defaults:
              run:
                  working-directory: restapi
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm ci --legacy-peer-deps
            - run: npm run migrateDb
            - run: npm test
    run_pull:
        name: run pull
        runs-on: ubuntu-latest
        needs: [unit-test-webapp, unit-test-restapi]
        
        steps:
            - uses: fifsky/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                user: ${{ secrets.SSH_USER }}
                key : ${{ secrets.SSH_PRIVATE_KEY }}
                args: -tt
                command: |
                  cd TFG
                  git fetch
                  git pull
                
            
    